export enum HttpRouteIdentifiers {
  /**
   * AUTH
   */
  AUTH_POST_LOGIN = 'AUTH_POST_LOGIN',
  AUTH_POST_REFRESH = 'AUTH_POST_REFRESH',
  AUTH_POST_REGISTER = 'AUTH_POST_REGISTER',

  /**
   * ADMIN
   */
  ADMIN_AUTH_POST_LOGIN = 'ADMIN_AUTH_POST_LOGIN',
  ADMIN_AUTH_POST_REFRESH = 'ADMIN_AUTH_POST_REFRESH',
  ADMIN_AUTH_POST_REGISTER = 'ADMIN_AUTH_POST_REGISTER',

  ADMIN_ACCOUNT_POST = 'ADMIN_ACCOUNT_POST',
  ADMIN_ACCOUNT_PUT = 'ADMIN_ACCOUNT_PUT',
  ADMIN_ACCOUNT_GET = 'ADMIN_ACCOUNT_GET',
  ADMIN_ACCOUNT_GET_ALL = 'ADMIN_ACCOUNT_GET_ALL',
  ADMIN_ACCOUNT_GET_MANY = 'ADMIN_ACCOUNT_GET_MANY',

  /**
   * PROFILE
   */
  PROFILE_GET = 'PROFILE_GET',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  PROFILE_DELETE = 'PROFILE_DELETE',

  /**
   * UTILS
   */
  GET_STATUS = 'GET_STATUS',
  GET_ROOT = 'GET_ROOT'
}
