version: '3.8'
services:
  proxy:
    image: traefik:2.3.4
    restart: always
    command:
      - --log.level=INFO
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.defaultRule=
      # CHANGE THE NAME OF THE NETWORK TO REFLECT THE CORRECT NAME
      - --providers.docker.network=swag_proxy
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.storage=/storage/acme.json
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/storage
    labels:
      traefik.enable: true
      traefik.http.routers.http-catchall.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: redirect-https
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: https
      traefik.http.middlewares.redirect-https.redirectscheme.permanent: true
    logging:
      options:
        max-size: 50m

  api:
    image: registry.appstud.com/swag-backend:develop
    restart: always
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`api.dev.swag.fr`)
      traefik.http.routers.api.entrypoints: web-secure
      traefik.http.routers.api.tls: true
      traefik.http.routers.api.tls.certresolver: myresolver
      traefik.http.services.api.loadbalancer.server.port: 8080

#####################
## NETWORK
#####################
networks:
  proxy:
    driver: bridge
