version: '3.1'
services:
  mongo:
    container_name: swag-mongo
    image: mongo:5.0.6-focal
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - "./mongo-share:/tmp/data"
      - "./mongo-data:/data/db"
