export enum Apotheose {
  NONE = 'NONE',
  NORMALE = 'NORMALE',
  IMPROVED = 'IMPROVED',
  FINALE = 'FINALE',
  ARCANIQUE = 'ARCANIQUE',
  FORME_VENGERESSE = 'FORME_VENGERESSE',
  SURCHARGE = 'SURCHARGE'
}
