export enum Bloodline {
  LUMIERE = 'LUMIERE',
  TENEBRE = 'TENEBRE',
  EAU = 'EAU',
  FEU = 'FEU',
  VENT = 'VENT',
  TERRE = 'TERRE',
  FOUDRE = 'FOUDRE',
  GLACE = 'GLACE',
  NAGA = 'NAGA',
  TROGLODYTE = 'TROGLODYTE',
  LYCAN = 'LYCAN',
  GOULE = 'GOULE',
  SUCCUBE = 'SUCCUBE',
  ILLITHIDE = 'ILLITHIDE',
  ARBRE = 'ARBRE',
  AUCUN = 'AUCUN'
}
