export enum Classe {
  CHAMPION = 'CHAMPION',
  CORROMPU = 'CORROMPU',
  REJETE = 'REJETE',
  PACIFICATEUR = 'PACIFICATEUR',
  SPIRITE = 'SPIRITE',
  ARCANISTE = 'ARCANISTE',
  CHAMPION_ARCANIQUE = 'CHAMPION_ARCANIQUE',
  SOLDAT = 'SOLDAT',
  AVATAR = 'AVATAR',
  SKINWALKER = 'SKINWALKER',
  INCONNU = 'INCONNU'
}
