name: production deploy workflow

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  build-docker:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup tags 1/2
        run: echo "CUSTOM_TAG=production-ci-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      - name: setup tags 2/2
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_HUB_REGISTRY }}/appstud-swag-backend-node
          tags: |
            production
            ${{ env.CUSTOM_TAG }}
      - name: login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            RELEASE_NUMBER="${GITHUB_SHA}-${GITHUB_RUN_NUMBER}"
