name: automatic testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    env:
      CI: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: run lint
        run: npm run lint
      - name: run tests
        run: npm run test
      - name: run sonar
        run: npm run sonar
        if: ${{ success() }} || ${{ failure() }}
